import random

list_of_technology = ["AAPL", "ACIW", "ACN", "ADBE", "ADI", "ADP", "ADSK", "AKAM", "AMD", "AMAT",
                      "ANET", "ANSS", "ARW", "ATVI", "AVGO", "AVT", "AZPN", "BA", "BB", "BLL",
                      "BLKB", "BR", "CDK", "CDNS", "CERN", "CHKP", "CIEN", "COMM", "COUP",
                      "CREE", "CRM", "CRUS", "CRWD", "CSCO", "CVLT",
                      "CY", "CYBR", "DBX", "DDD", "DDOG", "DLB", "DOCU", "DOX", "DXC", "EA", "EFX", "EQT",
                      "FCEL", "FDS", "FEYE", "FIT", "FTNT", "FVRR", "G", "GE", "GLW", "GPRO",
                      "GRMN", "GRPN", "HIMX", "HPE", "HPQ", "IAC", "IBM",
                      "INFO", "INTC", "IPGP", "IT", "JBL", "JCOM", "KEX", "LOGI",
                      "MCHP", "MSFT", "MCO", "MDB", "MDRX", "MOMO", "MSCI", "MSI", "MU", "NCR",
                      "NLOK", "NLSN", "NOW", "NUAN",
                      "NVDA", "NTAP", "NTGR", "NXPI", "OKTA", "ON", "PANW", "PAYX", "PBI",
                      "PCG", "PFPT", "PING", "PTC", "PINS", "QCOM", "ORCL", "QRVO", "OTEX", "SABR",
                      "SHOP", "SNAP", "SPCE", "SPGI", "SPLK", "SQ", "SSNC",
                      "STM", "STX", "SYY", "SWKS", "TEAM", "TER", "TEVA", "TLND",
                      "TSM", "TTWO", "TWLO", "VEEV", "VLO", "VMW", "VRSK", "VSAT",
                      "WDC", "WIX", "WORK", "ZM", "XRX", "ZBRA", "ZEN", "ZNGA", "ZS"]

list_of_materials = ["AA", "ATI", "BLL", "CCJ", "CENX", "CCK", "UFS", "EXP", "EGO", "FCX", "GPK",
                     "IP", "KGC", "LPX", "MLM", "NEM", "NUE", "OC", "OI", "PKG", "PAAS", "RS", "RGLD", "SON", "SCCO",
                     "TRQ", "X", "VALE", "VMC", "WPM", "AUY", "MMM", "AIV", "ALB", "APD", "ASH", "AVY", "CE", "CX",
                     "CF", "CTVA", "DOW", "DD", "EXP", "EMN", "ECL", "IFF", "FMC", "HUN", "ICL", "LYB", "MEOH", "MOS",
                     "NEU", "POL", "PPG", "RPM", "SHW", "SLGN", "SQM", "GRA", "WLK"]

list_of_communication_services = ["ACIA", "GOOG", "AMCX", "T", "BIDU", "CTL", "CHTR", "CHL", "CHU", "CHT",
                                  "CMCSA", "DISCA", "DISH", "DIS", "EXPE", "FFIV", "FB", "FOXA", "FTR", "GDDY",
                                  "GRUB", "IPG", "LBTYA", "LN", "LYFT", "MTCH", "NFLX", "OMC",
                                  "PINS", "RCI", "ROKU", "SBAC", "SNAP", "SPOT", "S", "TMUS", "TU", "TTD", "TRIP",
                                  "TWTR", "UBER", "VEON", "VZ", "VIAC", "WB", "YNDX", "Z"]

list_of_utilities_and_real_estate = ["AES", "AEE", "AEP", "AWK", "WTR", "ATO", "CMS", "ED", "DUK", "EIX", "EVRG",
                                     "EXC", "FE", "MDU", "NFG", "NEE", "NI", "NRG", "OGE", "PPL", "PEG", "SRE", "SO",
                                     "UGI", "XEL", "AGNC", "ARE", "AMH", "AVB", "BXP", "CPT", "CBL", "CBRE", "CB",
                                     "CLNY", "CXP", "ESS", "FRT", "GLPI", "JLL", "PB", "SVC", "SITC"]

list_of_energy = ["LNT", "AR", "APA", "BKR", "COG", "CNP", "CHK", "CVX", "SNP", "CNX", "CXO", "COP",
                  "CLB", "DCP", "DVN", "DO", "D", "DRQ", "DTE", "ENS", "EPD", "EOG", "EQT", "XOM", "FSLR", "GPOR",
                  "HAL", "HP", "HES", "HFC", "KMI", "LPI", "MMP", "MRO", "MPC", "MUR", "NBR", "NOV",
                  "NS", "OAS", "OXY", "OII", "OKE", "PBR", "PSX", "PXD", "QEP", "RRC", "RES", "SSL", "SLB", "SM",
                  "SWN", "SPWR", "TRGP", "FTI", "VAL", "VLO", "VSLR", "WLL", "WMB", "WEC", "INT"]

list_of_industrials = ["AOS", "AYI", "AEIS", "ACM", "AER", "AGCO", "ALLE", "ALSN", "AME", "APH", "AXE", "BA", "CAT",
                       "CLH", "CGNX", "CFX", "CR", "CSX", "CMI", "DE", "DCI", "DOV", "ETN", "EMR", "FAST", "FDX",
                       "FLEX", "FLS", "FLR", "GD", "GE", "GWR", "GLNG", "GGG", "HXL", "HON", "HII", "IEX", "ITW",
                       "IR", "ITRI", "JEC", "JCI", "KSU", "KBR", "KMT", "KEYS", "KEX", "KNX", "LII", "LECO", "LFUS",
                       "LMT", "MIC", "MIDD", "MSM", "NDSN", "NOC", "NSC", "ODFL", "PH", "PNR", "PWR", "RTN", "RBC",
                       "RSG", "ROK", "ROP", "R", "SPR", "SPXC", "TDY", "TEX", "TXT", "TTC", "TDG", "TRMB", "TRN", "UAL",
                       "URI", "UTX", "UNP", "UPS", "VMI", "WAB", "WM", "WCC", "XPO", "XYL"]

list_of_consumer_discretionary = ["ANF", "ADNT", "ALK", "BABA", "AMZN", "AAL", "AEO", "APTV", "ASNA", "AN", "AZO",
                                  "CAR",
                                  "BBBY", "BBY", "BJ", "BLMN", "BWA", "BV", "EAT", "BC", "BURL", "CAL", "GOOS", "CPRI",
                                  "KMX", "CRI", "CVNA", "CHWY", "CMG", "CHRW", "CNK", "CTAS", "COLM", "CPA", "CPRT",
                                  "DHI", "DAN", "DLPN", "DAL", "DKS", "DDS", "DOL", "DNKN", "EBAY", "ELF", "ETSY",
                                  "RACE", "FCAU", "FL", "F", "FBHS", "FOSL", "GME", "GPS", "GTX", "GPC", "GIL", "GM",
                                  "GNC", "GT", "HRB", "HBI", "HOG", "HAS", "HD", "H", "IGT", "IRBT", "ITT",
                                  "JPC", "SJM", "JD", "JBLU", "JMIA", "KAR", "KSS", "KTB", "LB", "LVS", "LEA", "LEG",
                                  "LEN", "LEVI", "LYV", "LKQ", "LOW", "LULU", "M", "MANU", "MAN", "MAR", "MAS", "MAT",
                                  "MCD", "MLCO", "MELI", "MGM", "MHK", "NWL", "NKE", "NIO", "JWN", "NVEE", "OSK",
                                  "PTON", "PDD", "PII", "POOL", "PHM", "PVH", "RL", "RVLV", "RHI", "RCL", "SBH",
                                  "SGMS", "SMG", "SEE", "SIX", "SNA", "LUV", "SAVE", "SWK", "SBUX", "TPR",
                                  "TEN", "TSLA", "MSG", "REAL", "TJX", "THO", "TIF", "TOL", "TSCO", "TUP",
                                  "ULTA", "UAA",
                                  "URBN", "VFC", "VC", "W", "WEN", "WHR", "WSM", "WW", "WYND", "WYNN"]

list_of_consumer_staples = ["MO", "ADM", "BYND", "BRFS", "BG", "CPB", "CHD", "CLX", "KO", "CL", "CAG", "STZ", "COTY",
                            "DG", "ENR", "EL", "FLO", "GIS", "HLF", "HLT", "HRL", "INGR", "K", "KDP", "KMB", "KHC",
                            "KR", "MKC", "TAP", "MDLZ", "PEP", "PM", "RAD", "SPB", "SFM", "SYY", "TGT",
                            "HAIN", "TSN", "UNFI", "VFF", "WBA", "WMT", "YUM"]

list_of_healthcare = ["ABT", "ABBV", "ACAD", "ALC", "ALXN", "ALGN", "ALKS", "AGN", "ALNY", "ABC", "AMGN", "ANTM",
                      "ARNA", "AVTR", "BHC", "BAX", "BDX", "BIO", "BIIB", "BMRN", "BSX", "BMY", "BKD", "BRKR", "CARA",
                      "CAH", "CNC", "CI", "COO", "CRBP", "CRSP", "CVS", "DHR", "DVA", "EW", "LLY", "EHC", "ENDP",
                      "EXAS", "GILD", "GWPH", "HCA", "HUM", "IDXX", "ILMN", "INCY", "INVA", "ISRG", "NVTA", "IQV",
                      "JAZZ", "JNJ", "LH", "LVGO", "MCK", "MD", "MDT", "MRK", "MTD", "MYL", "NGM", "OPK", "PKI",
                      "PFE", "QGEN", "REGN", "SGEN", "SYK", "TDOC", "TFX", "THC", "TEVA", "TMO", "TLRY", "UNH",
                      "UHS", "VAR", "VRTX", "WAT", "ZBH", "ZTS"]

list_of_financials = ["AFC", "AIG", "ACC", "AXP", "AMT", "AMP", "NLY", "AON", "ACGL", "ARCC", "AJG", "AIZ", "AGO",
                      "AXS", "BAC", "BK", "BKU", "BLK", "BOKF", "BRO", "COF", "CBOE", "CBRE", "SCHW",
                      "CIM", "CINF", "CIT", "C", "CME", "CNO", "CMA", "CBSH", "CXW", "BAP", "CCI", "CWK", "DLR", "DFS",
                      "DEI", "DRE", "ETFC", "EWBC", "EQIX", "EQR", "RE", "EXR", "FII", "FIS", "FNF", "FITB", "FHN",
                      "FRC", "BEN", "CFR", "GNW", "GPN", "GS", "HBAN", "PEAK", "HIG", "HST", "HHC", "IEP", "ICE",
                      "IBN", "IVZ", "IRM", "ITUB", "JKHY", "JHG", "JEF", "JPM", "KEY", "KRC", "KIM", "KKR", "LAZ",
                      "LM", "LC", "TREE", "LNC", "L", "LPLA", "MTB", "MKL", "MMC", "MA", "MET", "MTG", "MS", "NDAQ",
                      "NTRS", "NYCB", "ORI", "PYPL", "PBCT", "PNC", "BPOP", "PFG", "PSEC", "PRU", "RDN", "RJF",
                      "RLGY", "REG", "RF", "RGA", "RNR", "SEIC", "SBNY", "SLM", "SQ", "STT", "SF", "STI", "SIVB",
                      "SNV", "TROW", "AMTD", "ALL", "BX", "PGR", "TD", "TRV", "TFC", "TWO", "USB", "UBS",
                      "UMPQ", "UNM", "V", "WRB", "WBS", "WFC", "WELL", "WU", "WEX", "WLTW", "WETF", "ZION"]

european_stocks = ["ADS.DE", "ALO.PA", "BAYN.DE", "BMW.DE", "IFX.DE", "LHA.DE", "MAERSK-B.CO", "NOVO-B.CO",
                   "NZYM-B.CO", "SU.PA", "VWS.CO"]


def get_lists():
    print(len(list_of_industrials + list_of_technology + list_of_communication_services + list_of_energy +
              list_of_utilities_and_real_estate + list_of_materials + list_of_consumer_discretionary +
              list_of_consumer_staples + list_of_healthcare + list_of_financials))
    list_CFD = list_of_industrials + list_of_technology + list_of_communication_services + list_of_energy + \
               list_of_utilities_and_real_estate + list_of_materials + list_of_consumer_discretionary + \
               list_of_consumer_staples + list_of_healthcare + list_of_financials
    random.shuffle(list_CFD)
    return list_CFD


# investing side of Trading212

investing_list_of_energy = ["ADES", "AES", "ARPL", "AMRC", "AMSC", "APA", "ARCH", "AROC", "BKR", "BLDP", "BSM", "BCEI",
                            "COG", "CRC", "CPE", "CNQ", "CSIQ", "CQP", "CVX", "XEC", "CMS", "CRK", "CXO", "COP", "CEIX",
                            "CLR", "CZZ", "CVI", "DCP", "DVN", "DO", "FANG", "DRQ", "DTE", "ENB", "ET", "ENLC", "ENPH",
                            "ETR", "EPD", "EVA", "EOG", "EQT", "EQNR", "ES", "EXC", "EXTN",
                            "XOM", "FSLR", "FCEL", "GEOS", "HAL", "HP", "HES", "HEP", "JKS", "KMI", "KOS", "MMP", "MRO",
                            "MPC", "MPLX", "MUR",
                            "MUSA", "NC", "NOV", "NGS", "NEE", "DNOW", "OMP", "OXY", "OKE", "PBF", "BTU", "PBA",
                            "PBR", "PSX", "PSXP", "PXD", "PAA", "PLUG", "RRC",
                            "SLB", "SHLX", "SEDG", "SO", "SWN", "SPI", "SPWR", "RUN", "TRGP", "TRNX", "TRP", "FTI",
                            "TOT", "RIG", "VAL", "VLO", "VET", "VNOM", "VSLR", "VOC", "WES", "WMB", "WPX"]

investing_list_of_materials = ["MMM", "ASIX", "AEM", "AIV", "ADP", "ALB", "AA", "AMCR", "AU", "AVY", "BCPC", "BLL",
                               "GOLD", "BBL", "BHP", "BCC", "BREE.L", "CCJ", "CSL", "CRS", "CE", "CF", "CLF", "CDXS",
                               "BVN", "DOW", "DRD",
                               "DD", "EMN", "ESI", "UUUU", "EQX", "AG", "FMC", "FNV", "FCX", "GCP", "ICL", "IP", "IFF",
                               "LIN", "LAC", "LTHM", "LYB", "MLM", "MATW", "MDU", "NEM", "NXE", "NTIC", "NUE", "NTR",
                               "OI", "PAAS", "PPG", "RIO", "RGLD", "SAND", "SSL", "SCHN", "SEE", "SHW", "SBSW", "SMTS",
                               "SCOO", "STLD", "MOS", "TREX", "URG", "UEC", "VVV", "VRS", "VMC", "WRK", "WPM", "AUY"]

investing_list_of_industrials = ["AOS", "AIR", "ATU", "ADSW", "AEIS", "ACM", "AVAV", "ALG", "ALRM", "ALK", "ALGT",
                                 "ALLE", "AMOT", "AME", "APH", "AGX", "ATRO", "AAXN", "BMI", "BDC", "BHE", "BEST",
                                 "BLNK", "BE", "BA", "BGG", "CHRW", "WHD", "CAI", "CAMT", "CNI", "CARR", "CAT", "CFX",
                                 "CTG", "CPA", "CVA", "CYRX", "CSX", "CMI", "CW", "CYBE", "DE",
                                 "DAL", "DOV", "DYNT", "ETN", "ESLT", "EME", "EMR", "WATT", "ERII", "AQUA", "EXPD",
                                 "EXPO", "FAST", "FDX", "FLS", "FLR", "FORR", "FTV", "FRG", "FELE", "FTDR", "GLOG",
                                 "GLOP", "GD", "GE", "GFL", "EAF", "GHM", "HEES", "HDS", "HCCI",
                                 "HON", "HWM", "HUBB", "ICHR", "ITW", "IR", "IVAC", "ITRI", "JBHT", "J", "JBLU", "JBT",
                                 "JCI", "KAI", "KSU", "KEYS",
                                 "KE", "LHX", "LSTR", "LTM", "LECO", "LFUS", "LMT", "MAGS", "MNTX", "MRCY", "MIDD",
                                 "MTSC", "NSSC", "NATI", "LASR", "NAT", "NSC", "NOC", "NOVT", "ODFL", "OSIS", "OTIS",
                                 "PCAR", "PH", "PNR", "POWL", "PWR", "RBC", "RSG", "RGP",
                                 "RXN", "ROK", "ROP", "R", "SAIA", "SHIP", "SITE", "SNA", "LUV", "SAVE", "SPXC", "FLOW",
                                 "SXI", "SRCL", "TEL", "TNC", "TTEK", "TXT", "GBX", "HCKT", "SHYF", "TKR", "TOPS",
                                 "BLD", "TRNS", "TDG", "TRMB", "TWIN", "UNP", "UPS", "URI", "VSEC", "GWW", "WCN", "WM",
                                 "WTS", "WLDN", "WWD", "WKHS", "WRTC", "XYL", "ZTO"]

investing_list_of_consumer_discretionary = ["FLWS", "TWOU", "AAN", "ANF", "ACTG", "ACCO", "AEY", "ADNT", "ATGE", "AAP",
                                            "BABA", "AMZN", "AMC", "AAL", "APEI", "AMWD", "CRMT", "APTV", "ARC", "FUV",
                                            "ARCO", "ASGN", "AN",
                                            "AZO", "CAR", "AZEK", "BBSI", "BECN", "BBBY", "BBY", "BGSF", "BGFV", "BJRI",
                                            "BLMN", "APRN", "BOOT", "BWA",
                                            "BYD", "BRC", "BV", "BC", "BKE", "BLDR", "BURL", "CZR", "CAL", "CWH",
                                            "GOOS", "CPRI", "KMX", "CCL",
                                            "CVNA", "CSPR", "CATO", "FUN", "CHWY", "CMG", "CHH", "CHUY", "CNK", "CTAS",
                                            "CPRT", "CTVA", "CRVL", "CROX", "DHI", "DRI", "PLAY", "TACO",
                                            "DENN", "DKS", "DPZ", "DKNG", "EBAY", "ECL", "LOCO", "EEX", "ETSY",
                                            "FTCH", "RACE", "FCAU", "FCFS", "FVRR", "FL", "F", "FRSX", "FOR", "FOSL",
                                            "FOXF", "FRPT", "FNKO",
                                            "GME", "GPS", "GTX", "GM", "GNTX", "GPC", "GDEN", "GT", "GHG", "GFF",
                                            "GRWG", "GES", "HRB", "HBI", "HOG", "HAS",
                                            "HSII", "MLHR", "HIBB", "HLT", "HMSY", "HD", "HUD", "NSP", "TILE", "IRBT",
                                            "JD", "JMIA", "KELYA", "KEQU", "KFRC", "KBAL", "KSS", "KTB",
                                            "KFY", "KRUS", "LB", "LAKE", "LAUR", "LEG", "LEN", "LEVI", "LQDT", "LAD",
                                            "LYV", "LOW", "LULU", "M", "MANU",
                                            "MAN", "HZO", "MAR", "MAS", "MAT", "MCD", "MELI", "MTH", "METX", "MGM",
                                            "MOGU", "MCRI", "MNRO", "NRC", "EDU", "NWL", "NKE",
                                            "NIO", "JWN", "NCLH", "ORLY", "OSW", "OSTK", "PTON", "PENN", "PETQ", "PETS",
                                            "PDD", "PLNT", "PLYA", "PII", "RL", "PHM", "NEW", "PVH", "QRTEA", "RDIB",
                                            "RCII", "QSR", "RVLV", "RHI", "ROST", "RCL", "RUHN", "RUTH", "SBH", "SGMS",
                                            "SEAS", "SHAK", "SCVL", "SSTI", "SIG", "SIX", "SKY",
                                            "SKYW", "SNBR", "SLM", "SPWH", "SWK", "SBUX", "SHOO", "SFIX", "STRA",
                                            "TAL", "TPR", "TH", "TMHC", "TSLA", "TXRH", "CAKE", "PLCE", "MIK", "REAL",
                                            "WEN", "THO",
                                            "TIF", "TJX", "TOL", "TM", "TSCO", "TNET", "TBI", "ULTA", "UAA", "UNF",
                                            "UAL", "URBN", "VFC", "MTN", "VVI", "VIPS", "SPCE", "VSTO", "VRM", "WTRH",
                                            "WSG", "W", "WSTG", "WHR", "WING", "WINA", "WW", "WYND", "WYNN", "XSPA",
                                            "YUMC", "YUM", "YJ", "ZUMZ"]

investing_list_of_consumer_staples = ["MO", "BUD", "ADM", "BGS", "BYND", "BIG", "BJ", "BTI", "BF-A", "BG", "CALM",
                                      "CVGW", "CPB", "CELH", "CHD", "CLX", "KO", "CCEP", "CL", "CAG",
                                      "STZ", "COST", "COTY", "CRON", "DAR", "DEO", "DG", "DLTR", "ELF", "EL", "GIS",
                                      "GO", "HELE", "HLF",
                                      "HRL", "IMKTA", "IPAR", "SJM", "K", "KDP", "KMB", "KHC", "KR", "MKC", "MGPI",
                                      "TAP", "MDLZ", "MNST", "FIZZ", "OLLI", "PEP", "PAHC",
                                      "PM", "PPG", "PG", "RAD", "SAFM", "SPTN", "SYY", "TGT", "SAM", "CHEF", "HSY",
                                      "TSN", "UN", "UVV", "VFF", "WBA", "WMT", "WMK"]

investing_list_of_healthcare = ["TXG", "ABT", "ABBV", "ABMD", "ACIU", "ACHC", "ACAD", "AXDX", "XLRN", "ACOR", "AHCO",
                                "ADPT", "ADUS", "ADVM", "AERI", "AGEN", "AGRX", "A", "AGIO", "AIMT", "AKCA", "AKBA",
                                "AKRO", "AKUS", "ALBO",
                                "ALC", "ALEC", "ALXN", "ALGN", "ALKS", "ALLK", "AHPI", "ALLO", "ALNY", "AMRN", "AMED",
                                "AMS", "ABC", "AMGN", "FOLD", "AMN", "AMRX", "AMPH", "ANAB", "ANGO", "ANIP", "ANIK",
                                "ANPC", "ATRS", "ANTM", "APLS", "APHA", "AMEH", "APLT", "APRE", "APTO", "ARCT", "ARQT",
                                "ARDX",
                                "ARNA", "ARWR", "ARVN", "ASDN", "ASMB", "AZN", "ATRA", "ATNX", "ATHX", "BCEL", "ATRC",
                                "ATRI", "ACB", "AVDL", "AVNS", "AVTR", "AVGR", "AVRO", "AXNX", "AXGT", "AXSM",
                                "BXRX", "BHC", "BAX", "BEAM", "BDX", "BGNE", "BLCM", "BYSI", "TECH", "BASI", "BIOC",
                                "BCRX", "BDSI", "BIIB", "BLFS", "BMRN", "PHGE", "BNTX", "BSTC", "BEAT", "BTAI",
                                "BLUE", "BPMC", "BSX", "BBIO", "BMY", "BRKR", "BNR", "CABA", "CGC", "CARA",
                                "CRDF", "CAH", "CSII", "CDNA", "CSTL", "CPRX", "CNC", "CNTG", "CERS", "GIB", "CCXI",
                                "CBPO", "CPHI", "CI", "CLIN.L", "CLVS", "CODX", "COCP", "CHRS", "COLL", "CGEN", "CNST",
                                "CRBP", "CORT", "CRTX", "CVET", "CRNX", "CRSP",
                                "CCRN", "CUE", "CUTR", "CVS", "CBAY", "CYTK", "CTMX", "DHR", "DVA", "DCPH", "DNLI",
                                "XRAY", "DMTK", "DXCM", "DRNA", "DFFN", "DVAX", "EGRX", "EDIT", "EW", "LLY", "ENTA",
                                "ENDP", "EPZM", "ESPR", "ESTA", "EXAS", "EXEL", "FATE", "FGEN", "FMTX",
                                "FREQ", "FUSN", "GTHX", "GBIO", "GNPX", "GERN", "GILD", "GSK", "GBT", "GOSS", "GH",
                                "GHSI", "GWPH", "HALO", "HBIO", "HCA", "HQY", "HTBX", "HSIC", "HEPA", "HRTX", "HSKA",
                                "HEXO", "HOLX", "FIXX", "HZNP", "HUM", "IMAB", "IBIO", "ICLR", "ICUI", "IDXX", "IGMS",
                                "ILMN", "IMGN", "IMMU", "IMRN", "NARI", "INCY", "IFRX", "INMD", "INVA", "INGN", "INO",
                                "INSM", "PODD", "NTEC", "LOGM", "NTLA", "ICPT", "ISRG", "NVTA", "IONS", "IOVA", "IQV",
                                "IRTC", "IRWD", "JAZZ", "JNJ", "KALA", "KRTX", "KPTI", "KNSA", "KTOV", "KOD", "KRYS",
                                "KURA", "LH", "LTRN", "LNTH", "LMAT", "LHCG", "LGND", "LIVN", "LVGO", "LMNX", "MGNX",
                                "MDGL", "MGLN", "MNK", "MNKD", "MASI",
                                "MCK", "MEDP", "MDT", "MEIP", "MGTX", "MRK", "VIVO", "MMSI", "MRSN", "MRUS", "MTP",
                                "MRTX", "MIRM", "MRNA", "MTEM", "MNTA", "MORF", "MYL", "MYOK", "MYGN", "NSTG", "NH",
                                "NK", "NTRA", "NTUS", "NKTR", "NEOG", "NEO", "NBIX", "NXTC", "NGM", "NVS", "NVAX",
                                "NVO", "NVCR", "NUVA", "OCGN", "ODT", "OMER", "OTRK", "OPK", "OPCH", "OGEN", "OSUR",
                                "ORTX", "OGI", "OFIX", "KIDS", "OYST", "PACB", "PCRX", "PRTK", "PASG", "PDCO", "PAVM",
                                "PDLI", "PKI", "PRGO", "PFE", "PHAT", "PLRX", "PYPD", "PPD", "PRAH", "PGEN", "PRPO",
                                "DTIL", "PINC", "PRVL", "PRNB", "PROG", "PGNY", "PRTA", "PRVB", "PTCT", "PULM", "PLSE",
                                "PBYI", "QLGN", "QTRX", "DGX", "QDEL", "QTNT", "RDUS", "RDNT", "RAPT", "RETA", "RDHL",
                                "REGN", "RGNX", "RLMD", "RPTX", "RGEN", "REPL", "KRMD", "RTRX", "RVNC", "RVMD", "RYTM",
                                "RCKT", "RMTI", "RPRX", "RUBY", "SAGE", "SNY", "SRPT", "SRRK", "SGEN", "SNCA", "SWAV",
                                "SIBN", "SIGA", "SILK", "SINT", "SDC", "SOLY", "SRNE", "SWTX", "STAA", "STOK", "SYK",
                                "SNSS", "SUPN", "SGRY", "SRDX", "SNDX", "SYNH", "SNV", "SYRS", "TCMD", "TNDM", "TARO",
                                "TDOC", "TFX", "THC", "TEVA", "TGTX", "COO", "ENSG", "PRSC", "TXMD", "TBPH", "TMO",
                                "TLRY", "TMDI", "TTNP", "TVTY", "TBIO", "TMDX",
                                "TCDA", "TRIL", "TRIB", "GTS", "TPTX", "TWST", "RARE", "QURE", "UNH", "UTHR", "UHS",
                                "URGN", "VNDA", "VREX", "VAR", "VXRT", "VBIV", "VCYT", "VRTX", "VIE", "VMD", "VKTX",
                                "VIR", "VYGR", "WAT", "WST", "WMGI", "XBIT", "XNCR", "XENE", "YMAB", "ZLAB", "ZNTL",
                                "ZBH", "ZIOP", "ZTS", "ZGNX", "ZYXI"]

investing_list_of_financials = ["SRCE", "QFIN", "JFU", "AER", "AMG", "AFL", "AGMH", "AGNC", "AIG", "AL", "ALEX", "ADS",
                                "AB", "ALL", "ALLY", "AMBC", "AXP", "AMP", "ABCB", "AMSF", "NLY",
                                "AON", "ARI", "APO", "ACGL", "ARCC", "ARES", "AROW", "AJG", "APAM", "ASB", "AC", "AIZ",
                                "AGO", "AUB", "AXS", "BANF", "BSMX", "BAC", "BOH", "BMO", "BK", "BNS", "OZK", "BKU",
                                "BANR", "BBDC", "BCBP", "BRK-B",
                                "BLK", "BCOR", "BOKF", "BDGE", "BHF", "BRLIU", "BYFC", "BAM", "BPYU", "BRO", "CADE",
                                "CM", "COF", "CPTA", "CFFN", "CATM", "CATY", "CBTX", "SCHW", "CIM", "CB", "CCXX",
                                "CINF", "C", "CHCO", "CME", "CCH", "COLB", "CMA", "CBU",
                                "CODI", "COWN", "BAP", "CACC", "CRT", "CVBF", "DLR", "DFS", "DX", "ETFC", "EGBN",
                                "EHTH", "EFC", "ECPG", "ESGR", "EPR", "ERIE", "ESNT", "EVR", "FANH", "FIS", "FITB",
                                "BUSE", "FCNCA", "FFIN", "FHB", "FHN",
                                "FISV", "FLT", "FEAC", "WPF", "FMCI", "BEN", "FRHC", "FSK", "FULT", "FUSE", "FUTU",
                                "GATX", "GFN", "GNW", "GBCI", "GOOD", "GAIN", "GPN", "GL", "GS", "GSHD", "AJX", "GSKY",
                                "GDYN", "HLNE", "HASI", "HIG", "HDB", "HTLF", "HOPE", "HRZN", "HLI", "HSBC", "HBAN",
                                "IBKR", "ICE", "IVZ", "IVR", "ISBC", "ITUB",
                                "JKHY", "JRVR", "JHG", "JEF", "JFIN", "JPM", "KMPR", "KW", "KCAC", "KEY", "KNSL", "KKR",
                                "LADR", "LKFN", "LCA", "LAZ", "LGC", "LM", "TREE", "LX", "LNC", "L", "MTB", "MAIN",
                                "MFC", "MKL", "MMC",
                                "MA", "MCY", "MET", "MFA", "MC", "MGI", "MS", "COOP", "NDAQ", "NAVI", "NNI", "NRZ",
                                "NYMT", "NREF", "NKLA", "NMIH", "NTRS", "NWBI", "OCFC", "ONB", "ORI", "OXLC", "PPBI",
                                "PACW", "PLMR", "PKBK", "PAYC", "PYPL", "PAYS", "PBCT", "PNFP", "PNC",
                                "BPOP", "PFC", "PRA", "PGR", "PSEC", "PRU", "QIWI", "QD", "RDN", "RWT", "RF", "RNST",
                                "RPAY", "RY", "SAFT", "SASR", "SLCT", "SIGI", "SLQT", "FOUR", "SUNS", "SBSI", "SPAQ",
                                "SQ", "STWD", "STFC", "STT", "SCM", "STNE", "SLF", "SIVB", "SYF", "TROW",
                                "AMTD", "TCBI", "TFSL", "BX", "THG", "TRV", "TPRE", "TSBK", "TD", "SHLL", "TOWN.L",
                                "TSC",
                                "TFC", "TRUP", "TWO", "USB", "UMBF", "UMPQ", "UBSI", "UIHC", "UVE", "UNM", "VLY", "VEL",
                                "VCTR", "VBFC", "VIRT", "V", "WAFD", "WSBF", "WSBC", "WFC", "WAL", "WNEB", "WU", "WHG",
                                "WLTW", "WTFC", "XP", "ZION"]

investing_list_of_technology = ["ONEM", "DDD", "ATEN", "ACN", "ACIW", "ATVI", "ADBE", "ADTN", "AMD", "AGYS", "API",
                                "AIRG", "AKAM", "KERN", "AKTS", "MDRX", "AOSL", "AYX",
                                "AMBA", "AMSWA", "AMKR", "ASYS", "ADI", "PLAN", "ANSS", "ATEX", "APPF", "APPN", "AAPL",
                                "APDN", "AMAT", "AAOI", "ANET", "ARLO", "ASML",
                                "AZPN", "ASUR", "TEAM", "ATOM", "AUDC", "AEYE", "ADSK", "ADP", "AVNW", "AVID", "AVT",
                                "AWRE", "ACLS", "AXTI", "BAND", "BZUN",
                                "BNFT", "BILI", "BILL", "BLKB", "BB", "BL", "BAH", "BRQS", "EPAY", "BOX", "BCOV",
                                "AVGO", "BRKS", "CCMP", "CACI", "CDNS",
                                "CAMP", "CASA", "CDW", "CRNT", "CRNC", "CERN", "CEVA", "CHNG", "ECOM", "CHKP", "IMOS",
                                "CRUS", "CSCO", "CTXS", "CLFD", "CLDR", "NET", "CTSH",
                                "COHR", "COMM", "CPSI", "CNDT", "CLGX", "CSOD", "GLW", "CSGP", "COUP", "CREE", "CRWD",
                                "CSGS",
                                "CTS", "CUB", "CYBR", "DJCO", "DAKT", "DDOG", "DELL", "DSGX", "DGII", "DMRC", "APPS",
                                "DIOD", "DOCU", "DOMO", "DOYU", "DBX", "DSPG", "DXC", "EBON", "EBIX", "EGAN", "ESTC",
                                "EA",
                                "EMKR", "EMIS.L", "DAVA", "EIGI", "ENV", "EPAM", "PLUS", "EFX", "ERIC", "EVBG", "MRAM",
                                "EVH", "EXTR", "FFIV", "FDS", "FICO",
                                "FSLY", "FEYE", "FIT", "FIVN", "FLEX", "FLIR", "FORM", "FTNT", "FEIM", "GRMN", "IT",
                                "GNUS", "GILT", "GSB", "GLOB",
                                "GLUU", "GPRO", "GRVY", "GSIT", "GSX", "GTYH", "GWRE", "HLIT", "HPE", "HPQ", "HIMX",
                                "HUBS", "HUYA", "IBM", "IDEA.L", "IDEX", "INVE", "IDOX.L", "INFO", "IIVI", "IMMR",
                                "INFN",
                                "INOV", "IPHI", "INPX", "INSG", "NSIT", "INSE", "INTC", "IDCC", "INTU", "IPGP", "IQE.L",
                                "JCOM", "JBL", "JNPR", "KLAC",
                                "KOPN", "KLIC", "LRCX", "LTRX", "LSCC", "LDOS", "LLNW", "LPSN", "RAMP", "LIZI", "LOGI",
                                "LOGM", "LITE", "LUNA", "MTSI", "MGIC", "MANH", "MANT", "MKTX",
                                "MRVL", "MTLS", "MAXR", "MXIM", "MXL", "MCHP", "MU", "MSFT", "MSTR", "MIME", "MITK",
                                "MIXT", "MOBL",
                                "MODN", "MDB", "MPWR", "MCO", "MSI", "NPTN", "NTAP", "NTES", "NTGR", "NTCT",
                                "NEWR", "EGOV", "NICE", "NLSN", "NOK", "NLOK", "NVMI", "NUAN", "NTNX", "NVEC", "NVDA",
                                "NXPI", "OKTA", "OMCL",
                                "ON", "OCFT", "OSPN", "ORCL", "PD", "PANW", "PCYG", "PKE", "PAYX", "PCTY", "PCTI",
                                "PDFS", "PEGA", "PRFT", "PERI", "PFSW",
                                "PLAB", "PING", "PBI", "PXLW", "PLXS", "POWI", "PRGS", "PFPT", "PRO", "PTC", "QADA",
                                "QADB", "QRVO", "QCOM", "QLYS", "QMCO", "QTT", "RDCM", "RMBS", "RPD", "RTX", "RNWK",
                                "RP", "RDVT", "RESN", "RBBN", "RMNI", "RNG", "RIOT", "RST", "SBGI",
                                "SABR", "CRM", "SANM", "SAP", "SPNS", "SCSC", "SDGR", "SCPL", "SE", "SEAC", "STX",
                                "SCWX", "SMTC", "NOW", "SREV", "SWIR", "SILC", "SLAB", "SIMO", "SLP", "SITM", "SWKS",
                                "WORK", "SGH", "SMAR", "SMSI", "SMTX", "SONO", "SNE", "SPLK", "SPOT", "SPT", "SPSC",
                                "SSNC", "SRT", "SSYS",
                                "SMCI", "SVMK", "SYKE", "SYNC", "SYNA", "SNCR", "SNX", "SNPS", "TRHC", "TSM", "TTWO",
                                "TLND", "TM17.L", "TENB", "TDC",
                                "TER", "TXN", "TSEM", "TRU", "TTEC", "TTMI", "TWLO", "TYL", "UI", "UCTT", "UIS",
                                "UMC", "OLED", "UPLD", "UTSI",
                                "VRNS", "VECO", "VEEV", "VRNT", "VRSK", "VERI", "VSAT", "VIAV", "VICR", "VRTU", "VISL",
                                "VMW", "VCRA", "VOXX", "VUZI", "WAND.L", "WDC", "WIT", "WNS",
                                "WDAY", "WK", "XRX", "XLNX", "XPER", "XNET", "YEXT", "ZBRA", "ZEN", "ZUO", "ZNGA", "ZS"]

investing_list_of_communication_services = ["VNET", "EGHT", "ACIA", "ALLT", "GOOGL", "GOOG", "ANGI", "T", "ATNI",
                                            "ATHM", "BIDU", "BCE", "WIFI", "BKNG", "BOMN", "CABO", "CDLX", "CARG",
                                            "LUMN",
                                            "CHTR", "CHL", "CHU", "CHT", "CIDM", "CCOI", "CMCSA", "CVLT", "CMTL",
                                            "CNSL", "CRTO", "DADA", "DESP", "DISCA", "DISCK", "DISH", "SSP", "SATS",
                                            "EB",
                                            "EXPE", "FB", "FOXA", "FTR", "GCI", "GDDY", "GOGO", "GRPN", "GRUB", "HSTM",
                                            "IHRT", "IAC", "INAP", "IPG", "IQ",
                                            "IRDM", "KVHI", "LBRDA", "LBTYA", "LILA", "LTRPA", "LGF-B", "LORL",
                                            "LYFT", "MMYT", "MCHX", "MTCH", "MDP", "MOMO", "NCMI", "NFLX", "NWS", "OMC",
                                            "OPRA", "PTNR", "PT", "PINS", "QNST", "QRTEA", "MARK", "RCI", "ROKU", "SJR",
                                            "SHOP", "SSTK", "SINA", "SBGI", "SIRI", "SKM", "SNAP", "SOGO", "SOHU",
                                            "STMP", "TMUS", "TTGT", "TGNA", "TEF", "TU", "TME", "TTD",
                                            "TZOO", "TPCO", "TCOM", "TRIP", "TRVG", "TRUE", "TCX", "TWTR", "UBER",
                                            "UCL", "USM", "UONE", "UXIN", "VEON", "VRSN", "VZ", "VIAC",
                                            "VOD", "VG", "DIS", "WMG", "WB", "WIX", "WWE", "YNDX", "Z", "ZIXI", "ZM"]

investing_list_of_utilities_and_real_estate = ["AQN", "ALE", "LNT", "AEE", "AEP", "AWR", "AWK", "ATO", "AGR", "AVA",
                                               "AZRE", "BKH", "BIP", "BEP", "CIG", "CNP", "EBR", "ED", "CWCO", "D",
                                               "DUK", "EIX", "ENIA", "ENIC", "EVRG", "FE", "FTS", "GWRS", "HNP", "ITCI",
                                               "KEP", "MGEE", "NEP", "NI", "NRG", "OGS", "ORA", "PCG", "PNW", "POR",
                                               "PPL", "PEG", "RGCO", "SRE", "SWX", "SR", "SPH", "UGI", "UTL", "VST",
                                               "WEC", "XEL", "ADC", "ALEX", "ALX", "ARE", "ACC", "AFIN", "AMT", "COLD",
                                               "AHT", "AVB", "BXP", "BRX",
                                               "BPY", "CTRE", "CBL", "CBRE", "CDR", "CLDT", "CIO", "CLNY", "CXW", "COR",
                                               "CUZ", "CRESY", "CCI", "CUBE", "CONE", "DLR", "DEI", "DEA", "EGP",
                                               "ESRT", "EQIX", "ELS", "EQR", "ESS", "EXPI", "EXR", "FPI-PB",
                                               "FRT", "FPH", "FCPT", "GOOD", "LAND", "GNL", "HASI", "HTA", "PEAK", "HT",
                                               "HST", "HPP", "IIPR", "INVH", "IRM", "MAYS", "KIM", "LMRK", "LTC", "MAC",
                                               "CLI", "MGRC", "MPW", "MAA", "MNR", "NNN", "NMRK", "OHI", "PK", "DOC",
                                               "PLYM", "APTS", "PLD", "PSB", "PSA", "RYN", "O", "RVI", "REXR", "RLJ",
                                               "RMR", "SBRA", "SAFE", "BFS",
                                               "SBAC", "SPG", "SLG", "SRC", "STAG", "STOR", "SUI", "SHO", "SKT", "TRNO",
                                               "GEO", "UMH", "VTR", "VER", "VICI", "VNO", "WPC",
                                               "WELL", "WY", "WSR"]

investing_list_of_oct_nov = ["TCEHY", "NSRGY", "RHHBY", "LVMUY", "PNGAY", "LRLCY", "MPNGY", "PROSY", "CIHKY", "SFTBY",
                             "AAGIY", "DCMYY", "SIEGY", "HESAY", "CSLLY", "ENLAY", "CMWAY", "IDEXY", "CHDRY", "NTTYY",
                             "PPRUY", "NPSNY", "IBDRY", "ALIZY", "DTEGY", "FRCOY", "AIQUY", "SBGSY", "NTDOY", "RCRUY",
                             "CHGCY", "RBGLY", "ADDYY", "DNNGY", "KDDIY", "EADSY", "NJDCY", "DMLRY", "HKXCY", "ESLOY",
                             "SHECY", "DPSGY", "SOBKY", "BASFY", "ADYEY", "HEINY", "DSNKY", "DKILY", "ATLKY", "ATLCY",
                             "BYDDY", "OLCLY", "ZURVY", "VCISY", "VWAGY", "BAYRY", "BNPQY", "SMMNY", "MRAAY", "SAFRY",
                             "LZAGY", "DASTY", "NABZY", "PDRDY", "MTHRY", "BMWYY", "KNYJY", "HENKY", "HENOY", "WMMVY",
                             "NTOIY", "HOCPY", "TOELY", "AXAHY", "FANUY", "VLVLY", "DANOY", "IFNNY", "NILSY", "ANZBY",
                             "DBSDY", "AHCHY", "GVDNY", "LNSTY", "CFRUY", "ITOCY", "JAPAY", "WXXWY", "WFAFY", "VONOY",
                             "DSDVY", "DNZOY", "SUHJY", "ECIFY", "SMCAY", "FSUGY", "SXYAY", "VIVHY", "EXPGY", "MQBKY",
                             "KAOOY", "MURGY", "HTHIY", "JMHLY", "VWAPY", "TKOMY", "LGFRY", "VWDRY", "NRDBY", "YAHOY",
                             "ENGIY", "SMICY", "CLLNY", "NGLOY", "ADRNY", "GXYYY", "JPPHY", "AMKBY", "OPYGY", "CLPBY",
                             "ANPDY", "DBOEY", "WEGZY", "BDRFY", "RDSMY", "ELEZY", "EONGY", "MITSY", "HSNGY", "UNICY",
                             "SVNDY", "HNNMY", "OVCHY", "TRUMY", "MIELY", "HCMLY", "HXGBY", "TSCDY", "SCMWY", "SHZHY",
                             "CJPRY", "FJTSY", "FUJIY", "RWEOY", "OCPNY", "ALPMY", "PDYPY", "CMPGY", "SSDOY", "ASAZY",
                             "LBRDB", "TTNDY", "ZLNDY", "CRARY", "KHNGY", "UOVEY", "BRDCY", "JSHLY", "SDVKY", "AMADY",
                             "HKHHY", "CKHUY", "CLPHY", "ESALY", "NEXOY", "CTTAY", "KMTUY", "SSREY", "FERGY", "TELNY",
                             "KRYAY", "DNHBY", "NCLTY", "SAXPY", "AONNY", "KYOCY", "KUBTY", "FSNUY", "WTKWY", "ARZGY",
                             "KBCSY", "OCDDY", "OEZVY", "CODYY", "GBERY", "OTSKY", "SZKMY", "PCRFY", "LGRDY", "MITEY",
                             "TYIDY", "UCBJY", "EJPRY", "EDPFY", "AFTPY", "ANGPY", "CABGY", "MGDDY", "SOMLY", "MKKGY",
                             "GCTAY", "GASNY", "CGEMY", "SSMXY", "CRHKY", "SGSOY", "KNRRY", "BAESY", "SWDBY", "AKZOY",
                             "DWAHY", "EPOKY", "SSEZY", "DTCWY", "HVRRY", "SOTGY", "SYIEY", "UNCRY", "NRILY", "GIKLY",
                             "TLPFY", "FOJCY", "NCMGY", "ASBFY", "FRRVY", "NVZMY", "SMNNY", "GZPFY", "POAHY", "SAUHY",
                             "PUGOY", "TKAYY", "KNBWY", "NTDTY", "SVNLY", "ASHTY", "MTSFY", "AVIFY", "BDORY", "MSADY",
                             "KGSPY", "SCBFY", "SONVY", "NCBDY", "UPMMY", "IMBBY", "ERRFY", "OPHLY", "OMRNY", "THLLY",
                             "TTDKY", "FUJHY", "SGIOY", "SSUMY", "WRDLY", "PUMSY", "RKUNY", "RNECY", "GBLBY", "VDMCY",
                             "TEZNY", "EVVTY", "TSGTY", "ATASY", "CGXYY", "SMPNY", "DQJCY", "CHYHY", "CRRFY", "RTOKY",
                             "IKTSY", "XNGSY", "TGOPY", "JPXGY", "LNNGY", "GBOOY", "SCVPY", "DFKCY", "SCGLY", "AHKSY",
                             "WOPEY", "SWMAY", "MKTAY", "DNKEY", "NNGRY", "MONOY", "ILIAY", "CZMWY", "SKHHY", "HALMY",
                             "HDELY", "TOSYY", "HPGLY", "EDNMY", "SEOAY", "SGBLY", "SZLMY", "UBSFY", "SKHSY", "SZSAY",
                             "SWGAY", "NDEKY", "VEOEY", "FNMA", "STBFY", "FYRTY", "ASXFY", "HGKGY", "NXGPY", "BZLFY",
                             "RMYHY", "REPYY", "GNNDY", "AJINY", "BXBLY", "COIHY", "AUCOY", "JDSPY", "PSMMY", "JRONY",
                             "ALSMY", "YASKY", "CHEOY", "AMIGY", "KKOYY", "GJNSY", "JBAXY", "SNYFY", "SDXAY", "ATEYY",
                             "SUTNY", "RANJY", "NPSCY", "RDEIY", "YATRY", "MTUAY", "TKGSY", "HRGLY", "BNTGY", "UMICY",
                             "KIGRY", "MONDY", "KIROY", "JBSAY", "UHID", "MARUY", "COVTY", "YARIY", "SBSNY", "DSCSY",
                             "ORKLY", "SKFRY", "GNHAY", "KIKOY", "AYALY", "SMFKY", "SOLVY", "INGIY", "CCHGY", "TMVWY",
                             "SMMYY", "ASEKY", "SGPYY", "PUBGY", "QBIEY", "REMYY", "YAMCY", "EBKDY", "OTGLY", "SMTOY",
                             "IFJPY", "MTLHY", "AHEXY", "ALFVY", "DNTUY", "WJRYY", "MHGVY", "SKBSY", "KAEPY", "CUYTY",
                             "CNPAY", "ITTOY", "KSRYY", "LSRCY", "AGESY", "TLTZY", "ROHCY", "OMVKY", "KGFHY", "GLIBB",
                             "AAVMY", "LZRFY", "YKLTY", "RNLSY", "TMSNY", "SKSUY", "SNMCY", "PANDY", "SVCBY", "WILYY",
                             "HEGIY", "BDNNY", "CYGIY", "AEXAY", "TMICY", "SRTTY", "IMPUY", "GMVHY", "EFGSY", "HKMPY",
                             "UUGRY", "ARKAY", "STRNY", "ALNPY", "MNBEY", "TOTDY", "BKHYY", "ACSAY", "VLEEY", "SQNNY",
                             "KOTMY", "PRYMY", "ACOPY", "NNCHY", "CCOEY", "BURBY", "GLPEY", "IPSEY", "RTMVY", "SNPHY",
                             "ATDRY", "SMGZY", "TOKUY", "TISCY", "ISUZY", "ELUXY", "ACCYY", "SPXCY", "BTDPY", "BLHEY",
                             "ASGLY", "MCARY", "MAGOY", "VOPKY", "MDIBY", "TDHOY", "AMBBY", "BKGFY", "CRZBY", "AACAY",
                             "MAEOY", "FUPBY", "HLTOY", "GEHDY", "JSGRY", "DIFTY", "JAPSY", "PSZKY", "AMSSY", "EGIEY",
                             "SHCAY", "DNPLY", "BGAOY", "RGLXY", "CCLAY", "BMRRY", "HTCMY", "GEAGY", "LLESY", "IDKOY",
                             "ORINY", "RYKKY", "OUKPY", "TMRAY", "HSQVY", "CLZNY", "CKHGY", "NHYDY", "ENGGY", "WTBDY",
                             "JSAIY", "FMCC", "ASOMY", "HLUYY", "KAJMY", "RSNAY", "IESFY", "AGLXY", "JMPLY", "SALRY",
                             "SKLTY", "KNMCY", "LNEGY", "LRENY", "PEGRY", "DLAKY", "HLLGY", "CIBEY", "SHMUY", "PGENY",
                             "GTMEY", "YZCAY", "OSAGY", "MITUY", "WEGRY", "NPPNY", "CAKFY", "JCYGY", "LDSCY", "TSUKY",
                             "DCYHY", "YAMHY", "GNGBY", "HWDJY", "DMZPY", "JSCPY", "HKUOY", "TAIPY", "BNCDY", "AGRPY",
                             "PHPPY", "WRTBY", "SRGHY", "SCRYY", "AZIHY", "VLPNY", "RICOY", "RAIFY", "TYOYY", "SLOIY",
                             "CMSQY", "RYHTY", "BLSFY", "AVHNY", "TOPPY", "FELTY", "FCNCB", "NPSKY", "TSRYY", "TLGHY",
                             "EKTAY", "OCLDY", "TKAGY", "CDEVY", "EVTCY", "ASMVY", "CWLDY", "SUOPY", "BZZUY", "MAHLY",
                             "HINOY", "NKRKY", "NIPMY", "CHBAY", "VEMLY", "TEPCY", "ABCZY", "YOKEY", "FLGZY", "SHZUY",
                             "ROSYY", "MAURY", "FOVSY", "KYSEY", "BRTHY", "SEKEY", "TPRKY", "CLBEY", "GULRY", "CSXXY",
                             "CSIOY", "IMIAY", "TATYY", "JTTRY", "AUOTY", "FPRUY", "FMOCY", "THUPY", "WYGPY", "CLCGY",
                             "RBSFY", "IGGHY", "MCHOY", "ANSLY", "NGKSY", "MTGGY", "TKGBY", "RXEEY", "MZDAY", "THKLY",
                             "RNMBY", "ADRZY", "TPDKY", "KZMYY", "NCHEY", "EBRPY", "MNHFY", "AKABY", "KURRY", "SIETY",
                             "THYCY", "SGAMY", "ITJTY", "NDBKY", "HYPMY", "MALRY", "FINN", "KWPCY", "SKLKY", "SBFFY",
                             "NPNYY", "TKAMY", "AKBTY", "VNRFY", "DUFRY", "WBRBY", "TINLY", "GOFPY", "APELY", "CCOJY",
                             "ESYJY", "FINMY", "PBSFY", "EVNVY", "TGOSY", "BDVSY", "APNHY", "ELPVY", "STWRY", "CSNVY",
                             "AWCMY", "GLAPY", "NIFCY", "AIAGY", "GWPRF", "NHNKY", "EOCCY", "CGUSY", "MSLOY", "PUODY",
                             "JTEKY", "SOHVY", "BTVCY", "ZNKKY", "TKCBY", "SHWDY", "EBCOY", "DURYY", "ASCCY", "ISSDY",
                             "YORUY", "SREDY", "NTNTY", "BSEFY", "SFRGY", "CHRYY", "BCNAY", "KNCRY", "TBLMY", "TCCPY",
                             "MAKSY", "NINOY", "JGCCY", "PKCOY", "ETCMY", "MRPLY", "ANIOY", "MAUSY", "NPSHY", "BCUCY",
                             "FJTNY", "CBGPY", "BICEY", "SUBCY", "INCPY", "WETG", "ENGH", "FHNIY", "KWHIY", "IIJIY",
                             "JUMSY", "EFGXY", "IHICY", "FJTCY", "AOZOY", "TROLB", "KRNTY", "UBEOY", "BOSSY", "VIAAY",
                             "BPOSY", "BVNRY", "TRHFD", "BKUH", "OIBRQ", "FUWAY", "KUKAY", "ILKAY", "VTKLY", "TREAY",
                             "NPKYY", "THDDY", "CSVI", "TKYMY", "COGNY", "HAWPY", "SBLUY", "MMSMY", "RSTAY", "TGSGY",
                             "KPLUY", "FLIDY", "ASOZY", "HHULY", "SMSMY", "YITYY", "JPSWY", "WACLY", "TYOBY", "RKAGY",
                             "ISMAY", "MOHCY", "DNIYY", "KAIKY", "WACMY", "SYANY", "TCLRY", "SZGPY", "BOZTY", "BFLBY",
                             "WTBFA", "WTBFB", "CYBQY", "TDPAY", "PLFRY", "LTMAQ", "NVGI", "BIOGY", "FMBL", "ERMAY",
                             "TOGL", "CCGGY", "MDXG", "HWAL", "ADPXY", "VSBC", "HXOH", "FBAK", "HBIA", "FMCB", "USAT",
                             "TMOAY", "GANS", "NPACY", "NASB", "SBOEY", "BERK", "EMIS", "SPHRY", "RWWI", "LICT", "RTTO",
                             "SMLR", "SBNC", "KLDI", "MCHB", "KCLI", "CNND", "OTCM", "VADP", "ARTNB", "BHRB", "BWMYD",
                             "RCAR", "DGRLY", "CRCW", "SEMUF", "THVB", "FNGR", "AIXN", "FRMO", "EVSBY", "SCPJ", "MCCK",
                             "GFASY", "MGOM", "MCEM", "EOSS", "ATROB", "CUSI", "PKIN", "ORXOY", "AYAG", "FIZN", "EXSR",
                             "VLOWY", "TTSH", "MRTI", "CSHX", "SMTI", "ATCN", "FKWL", "LNNNY", "BVHBB", "WNDW", "NODB",
                             "HONT", "FNBT", "AMBZ", "CZFS", "JMSB", "GFKSY", "CFNB", "RCBC", "TGRF", "VNJA", "MLGF",
                             "VULC", "WMPN", "BKUT", "FCUV", "HLAN", "RZLTD", "WFTLF", "WNRP", "RVRF", "TRCY", "NECB",
                             "FFMH", "GDRZF", "ISBA", "EVOA", "CNBW", "CYFL", "WINSF", "TRUX", "NLST", "PURE", "TPRP",
                             "NWIN", "TYFG", "POWW", "PTGEF", "AKOM", "CWGL", "HMLN", "FKYS", "MDWT", "SCZC", "FNRN",
                             "GMGI", "BNCC", "LGIQ", "ENBP", "TYCB", "KSHB", "BVFL", "SBKK", "CHBH", "XTEG", "LQMT",
                             "LSYN", "QNBC", "PDER", "MHGU", "AERO", "KTYB", "RVRA", "BKUTK", "ICTSF", "EMYB", "MCBK",
                             "EACO", "CPKF", "MCBI", "JUVF", "CSBB", "CPTP", "PSIX", "CTGO", "NVOS", "BBBK", "OCBI",
                             "BAYK", "NUVR", "UTGN", "PSBQ", "LYBC", "NOBH", "EFSI", "CCFN", "KEWL", "BKGM", "JDVB",
                             "FGFH", "SCBH", "RRTS", "DMKBA", "MSBC", "DIMC", "ROFO", "HNFSA", "HNFSB", "APTL", "CVLBD",
                             "INTEQ", "HARL", "PFLC", "HSBI", "FABP", "NEFB", "SFDL", "LIXT", "FBTT", "EMPK", "WBBW",
                             "ELAMF", "PLTYF", "HWIN", "BMBN", "AMNF", "CMTV", "FFDF", "AMSIY", "SCTY", "CZBC", "ARHN",
                             "TYBT", "SOBS", "QEPC", "LWLG", "BHWB", "CNRD", "JFBC", "MODD", "BCAL", "CNBB", "KEGX",
                             "AMBK", "SABK", "PBAM", "MMMB", "ADOCY", "GWOX", "CURR", "ZMTP", "SOMC", "PRED", "CWBK",
                             "SILXY", "AVBH", "LBTI", "VABK", "WEBC", "REDW", "FETM", "CFCX", "NWYF", "BIOQ", "KTHN",
                             "GRRB", "FMBM", "PFOH", "UBNC", "SOTK", "INLB", "TRVR", "CLWY", "ELLH", "CCEL", "VLLX",
                             "SQCF", "MYBF", "CULL", "REEMF", "JCPNQ", "WAYN", "CZBT", "ELTP", "FACO", "TWCF", "CRSS",
                             "VKSC", "BURCA", "COSM", "WCRS", "ARBV", "CRAWA", "LINK", "IFHI", "SEBC", "LFGP", "KRPI",
                             "FISB", "CFST", "PKKW", "NACB", "DYNE", "MHPC", "TRNLY", "RVCB", "AVHOQ", "PFBX", "CNIG",
                             "KANP", "CHUC", "CBKM", "MCRAA", "MCRAB", "RSKIA", "SHWZ", "DWNX", "INVU", "HBSI", "PYYX",
                             "WLFDY", "SBBI", "UNIB", "UBAB", "CVSI", "CZNL", "WFCF", "PGTK", "FMFP", "TUESQ", "MFON",
                             "SCSG", "CNAF", "PMHG", "SMAL", "CIBY", "PKDC", "HLFN", "YDVL", "YRKB", "EPGNY", "FTMR",
                             "FFWC", "NIDB", "BTTR", "SHRG", "WLMS", "TETAA", "TETAB", "CFIN", "BELP", "NWPP", "MRMD",
                             "SBKO", "NUBC", "ECRP", "FMFG", "BOREF", "ACMTA", "ACMT", "BSHI", "IEHC", "UWHR", "FBVA",
                             "BSFC", "SRYB", "NJMC", "WEIN", "SLNG", "BEBE", "CTAM", "CUII", "SMID", "SUME", "EMGCQ",
                             "CEFC", "SRRE", "PPHI", "TLCC", "TTLO", "PGCG", "SBBG", "STBI", "ORBN", "WDFN", "FLFG",
                             "HFBA", "BUKS", "FOTB", "PCLB", "BCTF", "VKIN", "TPCS", "EQFN", "IOFB", "MUEL", "ATGN",
                             "NTRB", "FDVA", "PTBS", "OTTW", "PRSI", "VTDRF", "IVST", "SIMA", "CNCG", "GNRV", "CTUY",
                             "TORW", "STMH", "MDVT", "LSFG", "BORT", "KSBI", "PBSV", "TLRS", "MPAD", "BSPA", "ONVC",
                             "RYFL", "LEAT", "HRST", "PPBN", "BSCA", "OSBK", "FCOB", "PMTS", "HCBC", "FSRL", "TGEN",
                             "FBPA", "AFAP", "FBPI", "MEEC", "BEOB", "BKOR", "CCUR", "PGNN", "LOGN", "PWBO", "SLRK",
                             "HFBK", "ALMC", "CRMZ", "BMMJ", "GLGI", "EFBI", "OXBC", "BLHK", "UGRO", "SOFO", "OMQS",
                             "NANX", "PEGX", "SYCRF", "GVYB", "SFBK", "CIWV", "CFOK", "MACE", "MRGO", "BRBW", "PRKA",
                             "CNBZ", "SCTC", "PNBI", "CBCZ", "HLIX", "TMAK", "CNBX", "GOVB", "CHHE", "SCND", "SDRLF",
                             "HCBN", "DVCR", "JCDAF", "MAAL", "QNTO", "RSRV", "TRNF", "RWCB", "CZBS", "PBNK", "INIS",
                             "UNTN", "GTPS", "SCAY", "DTST", "AYSI", "SLGD", "STLY", "MVLY", "MNBO", "OTIVF", "GTMAY",
                             "EMMS", "FALC", "FBSI", "SCYT", "FRFC", "APLO", "SCXLB", "CBFC", "HCGI", "PEBC", "PHCG",
                             "CIBH", "PBCO", "IBWC", "NWBB", "CYTR", "SVBL", "GLXZ", "SPGZ", "WAKE", "OPXS", "ORBT",
                             "ADOM", "MKTY", "RYES", "WCFB", "TDCB", "CUEN", "PAYD", "CRSB", "HLSPY", "CCBC", "FRSB",
                             "FIDS", "OPST", "HRGG", "ELMA", "PIAC", "AGOL", "LXRP", "AMEN", "SSBP", "CTYP", "RAFI",
                             "PEYE", "JKRO", "TLSS", "GVFF", "DYNR", "FTLF", "CLOK", "DYSL", "EGDW", "MOBQ", "CCFC",
                             "TBBA", "SVIN", "CAWW", "PVBK", "HVLM", "DAFL", "FNFI", "FHLB", "SADL", "SNNF", "INBP",
                             "ERKH", "TRTC", "SECI", "IDWM", "TBTC", "SPND", "ABCP", "IVFH", "PPSF", "CNBA", "HWEN",
                             "NNUP", "HRTH", "GRMM", "PFHO", "AMFC", "RGBD", "CRZY", "NUKK", "FTDL", "AWSMD", "BXLC",
                             "DTRL", "TIKK", "ALTN", "ACAN", "KBPH", "ESOA", "OHPB", "NSYC", "GIGA", "ENZN", "TSSI",
                             "LPBC", "SUWN", "VFRM", "TRKX", "HWIS", "SURG", "BRRE", "FAME", "HCMC", "BMNM", "MAJJ",
                             "FCCT", "ZXAIY", "HOOB", "JSDA", "SPCO", "SMDM", "SYTE", "SNNY", "EFSH", "SENR", "NROM",
                             "CCOM", "VERF", "TOOD", "TOFB", "AMCT", "MXMTY", "OART", "IAIC", "SPRS", "ADMT", "AQSP",
                             "CIBN", "NAUH", "ANFC", "BKFG", "EUSP", "INRD", "HEWA", "QMCI", "CSTI", "ITEX", "JANL",
                             "LUVU", "DTRK", "IBAL", "VIDE", "CBKC", "MCVT", "ABLT", "ALPP", "SORT", "SUGR", "ALBY",
                             "AMMX", "MICR", "TCNB", "FSCR", "WELX", "VVUSQ", "RHDGF", "NEBLQ", "YEWB", "GNCIQ", "MGTI",
                             "FMBN", "PGNT", "XOGAQ", "CRVW", "YRIV", "EDHD", "ECIA", "SCIA", "IONI", "PALT", "SKTP",
                             "LCTC", "SRNA", "CLWD", "DWOG", "SRNN", "UNIR", "ABBB", "AAON", "ABB", "ACNB", "ABM",
                             "AGCO", "ACMR", "AHC", "ALJJ", "AMAG", "AMCX", "HKIB", "AMRK", "APG", "AACG", "ABIO",
                             "LIFE", "ASX", "AZZ", "ABEO", "AXAS", "ACAM", "ACEL", "ARAY", "ACER", "ACRX", "ACRS",
                             "ACU", "ATV", "AYI", "GOLF", "ADMS", "AE", "ADAP", "ADXN", "ADIL", "ACET", "ADRO", "AEHR",
                             "ADXS", "AEGN", "AMTX", "ACY", "AGLE", "AJRD", "WMS", "AEMD", "AIH", "ARPO", "AGFS",
                             "ALRN", "AIM", "AIRI", "AIRT", "ATSG", "ANTE", "AKTX", "AKER", "ALSK", "AIN", "ALDX",
                             "ALRS", "ALCO", "ALIM", "WTER", "Y", "ATI", "ABTX", "ALNA", "AESE", "ALSN", "ATEC", "ALPN",
                             "ALTG", "ALTA", "ALTR", "ALT", "ATHE", "ATUS", "AIMC", "ALTM", "ACH", "AMAL", "ABEV",
                             "AMBO", "DIT", "AMTB", "AMTBB", "UHAL", "AMRH", "AMX", "AMOV", "AXL", "AEO", "AEL", "AFG",
                             "ANAT", "AMNB", "AOUT", "ARL", "ARA", "AREC", "AMRB", "AVD", "AVCT", "ASRV", "ATLO",
                             "AMPE", "AMHC", "AMPY", "AXR", "AMYT", "AMRS", "AVXL", "ANCN", "ANDE", "ANIX", "ANVS",
                             "AR", "APEX", "APOG", "AINV", "APEN", "AIT", "AGTC", "AMTI", "ATR", "APVO", "APTX", "APYX",
                             "AQMS", "ARMK", "ARAV", "RKDA", "ARCB", "ACA", "ARNC", "RCUS", "ARGX", "ARDS", "ARKR",
                             "ARMP", "AFI", "AWI", "ARW", "ARTL", "ARTNA", "ARTW", "ABG", "AINC", "ASH", "ASLN", "ASPN",
                             "ASPU", "AWH", "ASRT", "AMK", "ASFI", "ASTE", "ALOT", "ASTC", "ATKR", "AAME", "ACBI",
                             "ATLC", "AAWW", "ATCX", "ATOS", "AUBN", "JG", "ALV", "AUTL", "AUTO", "AWX", "AVYA", "AVEO",
                             "ATXI", "CDMO", "AVNT", "RCEL", "AXLA", "AX", "AYLA", "AYTU", "AZYO", "BBX", "AZUL",
                             "AZRX", "BGCP", "BBQ", "RILY", "BKTI", "BRP", "BMCH", "BWXT", "BW", "BCSF", "BTN", "BBAR",
                             "BBD", "BBDO", "BBVA", "BCH", "BMA", "SAN", "BSAC", "BSBR", "CIB", "TBBK", "BXS", "BANC",
                             "BFC", "BMRC", "BOCH", "BPRN", "BKSC", "BFIN", "BSVN", "BWFG", "BHB", "BCS", "BNED", "B",
                             "BRN", "BSET", "BATL", "BCML", "BBGI", "BZH", "BELFA", "BELFB", "BLPH", "BRBR", "BNTC",
                             "WRB", "BRK-A", "BHLB", "BERY", "BRY", "XAIR", "BCYC", "BRPA", "BH", "BH-A", "BIO-B",
                             "BIO", "BPTH", "BCDA", "BMRA", "BLRX", "BSGM", "BVXV", "BHTG", "BIVI", "BFRA", "BITA",
                             "BKI", "BKCC", "TCPC", "BCAT", "BLBD", "BRBS", "BLCT", "BXC", "BXG", "BSBK", "BIMI",
                             "BPFH", "BWL-A", "BCLI", "BWAY", "BRFS", "BAK", "LND", "BBI", "BLIN", "BWB", "BRID",
                             "MNRL", "BFAM", "BEDU", "BSIG", "BCO", "VTOL", "BWEN", "BKD", "BRKL", "BMTC", "BSQR",
                             "BBW", "BFST", "BY", "CFFI", "CBFV", "CBZ", "YCBD", "CBMB", "CBOE", "CDK", "CECE", "CFBK",
                             "CHFS", "CIT", "CHPM", "CKX", "CVU", "CNA", "CCNE", "CEO", "CRAI", "CPSH", "CNO", "CRH",
                             "CSPI", "CSWI", "CTIC", "CNX", "CVV", "CBT", "CDZI", "CLBS", "CALB", "CWT", "CALA", "ELY",
                             "CALT", "CLXT", "CEI", "CATC", "CAC", "CANF", "CGIX", "CANG", "CNNE", "CAJ", "CMD", "CPHC",
                             "CCBG", "CBNK", "CSU", "CSWC", "CPST", "CAPR", "CSTR", "CG", "CUK", "CSV", "PRTS", "TAST",
                             "CARS", "CARE", "CWST", "CASY", "CASI", "CASS", "SAVA", "CSLT", "CATB", "CTLT", "CBIO",
                             "CVCO", "CVM", "CELC", "APOP", "CLDX", "CLRB", "CLLS", "CLSN", "CBMG", "CYAD", "CPAC",
                             "CX", "CETX", "CDEV", "EBR", "CENT", "CENTA", "CPF", "CEPU", "CVCY", "CENX", "CNBKA",
                             "LEU", "CNTY", "CCS", "CERC", "CDAY", "CSBR", "CHX", "CHRA", "CHAQ", "CTHR", "CRL", "GTLS",
                             "CCF", "CKPT", "CMCM", "CEMI", "CHE", "CC", "CHMG", "LNG", "CPK", "CHMA", "CVR", "CSSE",
                             "CHS", "CREG", "CMRX", "CAAS", "JRJC", "CEA", "LFC", "ZNH", "SNP", "CHA", "CGA", "DL",
                             "CXDC", "HGSH", "CJJD", "CNET", "COE", "CIH", "COFS", "CDXC", "CHDN", "CDTX", "CBB",
                             "CNNB", "CIR", "CZNC", "CTRN", "CTXR", "CFG", "CIZN", "CIA", "CZWI", "CIVB", "CLAR", "CLH",
                             "CLSK", "CCO", "CLSD", "CLIR", "CLRO", "CLPT", "CLW", "CWEN-A", "CWEN", "CBLI", "CNSP",
                             "CNF", "CCB", "COKE", "KOF", "CODA", "CCNC", "CVLY", "CDE", "JVA", "CGNX", "CNS", "CWBR",
                             "COHN", "CLCT", "CGRO", "CLGN", "CBAN", "CLBK", "COLM", "CMCO", "CBSH", "CMC", "CVGI",
                             "ESXB", "CYH", "TCFC", "CFBI", "JCS", "CTBI", "CWBC", "CIG-C", "CBD", "SID", "SBS", "ELP",
                             "CCU", "CMP", "CIX", "SCOR", "CHCI", "LODE", "CNCE", "CCM", "BBCP", "CNFR", "CNMD", "CNOB",
                             "CONN", "STZ-B", "ROAD", "CPSS", "TCS", "MCF", "CFRX", "VLRS", "CTRA", "CPS", "CTB", "CTK",
                             "CORE", "CMT", "CRMD", "CNR", "CLDB", "CRVS", "ICBK", "CPAH", "CVLG", "CBRL", "BREW", "CR",
                             "CRD-B", "CRD-A", "CRTD", "CREX", "CS", "CCAP", "CXDO", "CFB", "CRWS", "CCK", "CRY", "CTO",
                             "CFR", "CULP", "CPIX", "CRIS", "CURO", "CUBI", "CYAN", "CYCC", "CYCN", "CTEK", "CTSO",
                             "BOOM", "DHX", "DLHC", "DXPE", "DFPH", "DARE", "DQ", "DRIO", "DSKE", "DAIO", "DTSS",
                             "DWSN", "DXR", "DECK", "DCTH", "DK", "DLA", "DEN", "DLX", "DBI", "DXLG", "DHIL", "DBD",
                             "DRAD", "DGLY", "DCOM", "DMS", "DIN", "DISCB", "DXYN", "RDY", "DLB", "UFS", "DCI", "DGICA",
                             "DGICB", "RRD", "DFIN", "DORM", "PLOW", "DVD", "DPW", "DS", "DCO", "DLTH", "DUOT", "DXF",
                             "DRRX", "DYAI", "DY", "DT", "DZSI", "EDAP", "EH", "E", "EVOP", "EVI", "EBMT", "FCRD",
                             "EXP", "ESTE", "EWBC", "EML", "EAST", "ECHO", "MOHO", "EC", "EPC", "EDNT", "EDUC", "EIGR",
                             "BCOW", "ETNB", "EKSO", "ELAN", "ELSE", "ELMD", "ELVT", "ESBK", "ELOX", "EMAN", "AKO-A",
                             "AKO-B", "EMCF", "ERJ", "EBS", "MSN", "EIG", "EDN", "WIRE", "EHC", "EFOI", "ENR", "NDRA",
                             "ENS", "EPAC", "ENG", "EBF", "ENOB", "NPO", "ENSV", "ETTX", "ENTG", "ETM", "EBTC", "EFSC",
                             "EVC", "ELA", "ENZ", "NVST", "EQH", "ETRN", "EQBK", "EQS", "ERYP", "ESCA", "ESE", "ESP",
                             "ESSA", "ESQ", "GMBL", "WTRG", "ETH", "EEFT", "EVBN", "EVLO", "EVK", "EVER", "EPM", "EVOK",
                             "EVOL", "EOLS", "XGN", "XCUR", "EXLS", "XONE", "EXPC", "EXPR", "EZPW", "EYEG", "EYEN",
                             "FFG", "FNB", "FNCB", "FBK", "FFBW", "FSBW", "FTSI", "FRPH", "FCN", "FLMN", "SFUN", "DUO",
                             "FARM", "FMAO", "FMNB", "FARO", "FBSS", "AGM-A", "AGM", "FSS", "FHI", "FNHC", "FOE",
                             "FDBC", "FNF", "FDUS", "FRGI", "JOBS", "FISI", "FINV", "FAF", "FNLC", "FBNC", "FBMS",
                             "FRBA", "FBIZ", "FCAP", "FCBP", "FCF", "FCCO", "FCBC", "FCCY", "FFBC", "THFF", "FFNW",
                             "FFWM", "FGBI", "INBK", "FIBK", "FLIC", "FRME", "FMBH", "FMBI", "FXNC", "FNWB", "FSFG",
                             "FSEA", "FUNC", "FUSB", "MYFW", "SVVC", "FBC", "FIVE", "WBAI", "FPRX", "FVE", "BDL",
                             "FLXS", "FLXN", "FPAY", "FND", "FTK", "FLO", "FLNT", "FFIC", "FLUX", "FLY", "FOCS", "FMX",
                             "FONR", "FORTY", "FRTA", "FBRX", "FBHS", "FET", "FWRD", "FWP", "FIII", "FSTR", "FBM",
                             "FEDU", "FOX", "FRAN", "FC", "FRAF", "RAIL", "FMS", "FRD", "FTEK", "FSKR", "FUBO", "FULC",
                             "FLGT", "FLL", "FUL", "FF", "FTFT", "FVCB", "GBL", "GLIBA", "JOB", "GDS", "GWGH", "GPX",
                             "GVP", "GIII", "GTT", "GXGX", "GMS", "GAIA", "GLPG", "GALT", "GRTX", "GARS", "GENC",
                             "GNSS", "GNRC", "GMO", "GCO", "GENE", "GEN", "GNFT", "GNE", "GMAB", "GNMK", "GNCA", "THRM",
                             "GOVX", "GGB", "GABC", "ROCK", "GLAD", "GLT", "GKOS", "GLBZ", "GSAT", "GMED", "GBLI",
                             "GLYC", "GOL", "GFI", "GORO", "AUMN", "GV", "GSBD", "GBDC", "GTIM", "GDP", "GRSV", "GHIV",
                             "GRC", "GRA", "GGG", "GHC", "GRAM", "GTE", "LOPE", "GVA", "GPK", "GTN", "GTN-A", "GECC",
                             "GEC", "GLDD", "GSBC", "GWB", "GRBK", "GDOT", "GPRE", "GCBC", "GHL", "GNLN", "GNRS",
                             "GRNQ", "GEF", "GEF-B", "GSUM", "GRIF", "GRFS", "GRTS", "GPI", "GGAL", "SIM", "TV", "OMAB",
                             "PAC", "ASR", "AVAL", "SUPV", "GSH", "GNTY", "GFED", "GIFI", "GURE", "GPOR", "GYRO", "HBT",
                             "HCHC", "HCI", "HFFG", "HMNF", "HNI", "HTGM", "HVBC", "HAE", "HAIN", "HLG", "HNRG", "HOFV",
                             "HALL", "HBB", "HWC", "HJLI", "HNGR", "HAFC", "HONE", "HMY", "HARP", "HROW", "HSC", "HCAP",
                             "HVT", "HVT-A", "HE", "HA", "HWKN", "HWBK", "HAYN", "HCSG", "HHR", "HCAT", "HTLD", "HL",
                             "HEI-A", "HLIO", "HSDT", "HLX", "HMTV", "HNNA", "HTBK", "HRI", "HTGC", "HFWA", "HRTG",
                             "HESM", "HXL", "HX", "HPR", "HPK", "HIL", "HI", "HGV", "HIFS", "HQI", "HSTO", "HOL", "HFC",
                             "HOMB", "HBCP", "HFBL", "HMST", "HTBI", "HMC", "HOFT", "HOOK", "HMN", "HBNC", "HZN",
                             "TWNK", "HOTH", "HWCC", "HOV", "HBMD", "HHC", "HUBG", "HTHT", "HEC", "HSON", "HDSN",
                             "HUIZ", "HGEN", "HII", "HUN", "HURC", "HURN", "HCM", "HYMC", "IDT", "HYRE", "HY", "IAA",
                             "ICFI", "ICCH", "ICAD", "IEC", "IROQ", "IESC", "IFMK", "IMAC", "IRS", "ITCB", "ITT", "IBN",
                             "ICON", "IEP", "IDA", "ICLK", "IPWR", "IDYA", "IEX", "IDRA", "IKNX", "ISNS", "IMBI",
                             "IMRA", "ICCC", "IMNPQ", "IMH", "IMMP", "IMVT", "IMUX", "PI", "ICD", "IHC", "INDB", "IBCP",
                             "IBTX", "IBA", "INFI", "III", "INFY", "ING", "INFU", "IEA", "NGVT", "INGR", "INOD", "ISIG",
                             "IOSP", "ISSC", "INSP", "INWK", "IIIN", "NSPR", "IBP", "IPHA", "INMB", "IHT", "INS", "IDN",
                             "ITGR", "IHG", "INTG", "IBOC", "IMXI", "IDXG", "IPV", "XENT", "ICMB", "INTT", "IVC", "IIN",
                             "IPI", "INUV", "ISTR", "ITIC", "NVIV", "IO", "IRMD", "IRIX", "IRCP", "ISR", "ISDR", "ITP",
                             "ITMR", "ITI", "IIIV", "ISEE", "YY", "JJSF", "JAX", "JILL", "JACK", "BOTJ", "JHX", "JAN",
                             "JELD", "JRSH", "JT", "JYNT", "JLL", "JNCE", "JP", "JIH", "KAR", "KB", "KBR", "KLXE", "KT",
                             "KDMN", "KALU", "KLDO", "KLR", "KALV", "KAMN", "KSPN", "KBH", "KRNY", "KELYB", "KMPH",
                             "KMT", "KFFB", "KROS", "KTCC", "KZR", "KIN", "KC", "KINS", "KFS", "KTRA", "KEX", "KIRK",
                             "KNL", "KNX", "KN", "KOP", "KOSS", "KTOS", "KRA", "KRO", "LCNB", "LGL", "LPL", "LGIH",
                             "LKQ", "LCII", "DFNS", "LMFA", "LPLA", "LXU", "LYTS", "LJPC", "LZB", "LAIX", "LSBK",
                             "LBAI", "LW", "LANC", "LNDC", "LARK", "LE", "LCI", "LPI", "LRMR", "LAWS", "LAZY", "LEAF",
                             "LEA", "LPTX", "LEE", "LEGH", "LEGN", "LACQ", "LC", "LEN-B", "LII", "LEVL", "LBRT", "LWAY",
                             "LFVN", "LCUT", "LTBR", "LPTH", "LITB", "LSAC", "LMST", "LMB", "LMNR", "LINC", "LIND",
                             "LNN", "LCTX", "LN", "LINX", "LGHL", "LIQT", "LQDA", "LOAK", "LIVE", "LIVX", "LXEH", "LYG",
                             "LMPX", "LOGC", "LOMA", "LONE", "LGVW", "LOOP", "LPX", "LOVE", "LUB", "LL", "LBC", "LDL",
                             "LYRA", "MBI", "MDC", "MTG", "MHO", "MKSI", "MMAC", "MRC", "MSA", "MSM", "MSGN", "MTBC",
                             "MVBF", "MVC", "MYRG", "MCBC", "MFNC", "MIC", "MSGS", "MSGE", "MGTA", "MX", "MGY", "MGYR",
                             "MNSB", "MBUU", "MLVF", "TUSK", "MTW", "MTEX", "MN", "MMI", "MCS", "MRIN", "MPX", "MRNS",
                             "MRLN", "MBII", "MRTN", "MTZ", "MHH", "MCFT", "MTDR", "MTRN", "MTNB", "MTRX", "MATX",
                             "MLP", "MMS", "MEC", "MKC-V", "MUX", "MTL-P", "MTL", "MFIN", "MDLA", "MDIA", "MED", "MDGS",
                             "MD", "MCC", "MDLY", "MLCO", "MBWM", "MERC", "MBIN", "MFH", "MREO", "MCMJ", "MRBK", "EBSB",
                             "MTOR", "MACK", "MESA", "MLAB", "CASH", "MEI", "MCBS", "MCB", "MXC", "MFGP", "MVIS",
                             "MBOT", "MPB", "MSVB", "MBCN", "MSEX", "MOFG", "MLSS", "MLND", "MLR", "MIND", "MTX",
                             "NERV", "MGEN", "MSON", "MG", "MUFG", "MFG", "MBT", "MOD", "MWK", "MKD", "MBRX", "MOH",
                             "TAP-A", "MKGI", "MNPR", "MRCC", "MR", "MOG-A", "MOG-B", "MORN", "MOR", "MOSY", "MPAA",
                             "MOTS", "MOV", "MOXC", "MLI", "MWA", "GRIL", "MBIO", "MYE", "MYO", "MYOS", "NBTB", "NCR",
                             "NCSM", "NL", "NNBR", "NVEE", "NNVC", "NNDM", "NAOV", "NATH", "NBHC", "NKSH", "NHC", "NFG",
                             "NGHC", "NGG", "NHLD", "NPK", "NSEC", "EYE", "NWLI", "NAII", "NTCO", "NHTC", "NGVC",
                             "NATR", "NWG", "NTZ", "NAV", "NAVB", "NP", "NMRD", "NLTX", "NEON", "NEOS", "NEPH", "NSCO",
                             "UEPS", "NTWK", "NTIP", "NURO", "NTRP", "STIM", "NBSE", "NRBO", "NVRO", "GBR", "NFE",
                             "NWHM", "NJR", "NMFC", "NPA", "NYC", "NYCB", "NYT", "NBEV", "NWGI", "NEU", "NR", "NEWT",
                             "NEX", "NXST", "NEXT", "NODK", "NXGN", "NCBS", "NINE", "NOAH", "NMR", "NDLS", "NDSN",
                             "NSYS", "NBN", "NOG", "NFBK", "NRIM", "NWN", "NWPX", "NWE", "NWFL", "NVFY", "NVUS", "NUS",
                             "NCNA", "NUZE", "OGE", "OLB", "NXTD", "NES", "OFS", "OIIM", "OPBK", "OVLY", "OCSL", "OCSI",
                             "OAS", "OBLN", "OBLG", "OBCI", "OPTT", "OII", "OFED", "OCN", "OCUL", "OMEX", "OVBC", "ODC",
                             "OIS", "OPOF", "OSBC", "OLN", "ZEUS", "OFLX", "ONDK", "ONCS", "OCX", "ONCT", "PIH", "YI",
                             "OMF", "ONEW", "ONTO", "OOMA", "LPRO", "OPNT", "OPRT", "OPY", "OCC", "OPHC", "OPRX",
                             "ORMP", "OPTN", "ORAN", "ORBC", "OEG", "ORGS", "ONVO", "ORGO", "OBNK", "ORIC", "OESX",
                             "ORN", "IX", "ORRF", "OSK", "OSN", "OTEL", "OTIC", "OTTR", "OTLK", "OSG", "OVID", "OVV",
                             "OC", "ORCC", "OXM", "PFIN", "PDLB", "PAE", "PTSI", "CNXN", "PCB", "PCSB", "PDCE", "PICO",
                             "PGTI", "PJT", "PHI", "PKX", "PNM", "PRAA", "PRGX", "PUYI", "PMBC", "PKG", "PTN", "PAM",
                             "PHX", "PZZA", "PAR", "PARR", "PZG", "TEUM", "PRK", "PKOH", "PSN", "PTRS", "PBHC", "PATK",
                             "PNBK", "PATI", "PTEN", "PDSB", "PGC", "PSO", "PED", "PVAC", "PNTG", "PNNT", "PFLT",
                             "PWOD", "PAG", "PEN", "PEBO", "PEBK", "PFIS", "PRCP", "PRDO", "PFGC", "PFMT", "PESI",
                             "PPIH", "PRSP", "PSNL", "TLK", "PTR", "PBR-A", "PFNX", "PHAS", "FENG", "DNK", "PHR",
                             "PHUN", "PIRS", "PBFS", "PPSI", "PIPR", "PAGP", "PLAG", "PLT", "AGS", "PLBC", "PSTI",
                             "PSTV", "PLXP", "PTE", "PTMN", "POST", "PBPB", "PWFL", "PQG", "PFBC", "POAI", "PLPC",
                             "PFBI", "PBH", "PSMT", "PNRG", "PRIM", "PFG", "PDEX", "PRTH", "IPDN", "PFHD", "PFIE",
                             "PRPH", "PUMP", "PROS", "PB", "PLX", "TARA", "PTGX", "PTVCA", "PTVCB", "PTI", "PVBC",
                             "PROV", "PFS", "PBIP", "PUK", "PMD", "PCYO", "PSTG", "PRPL", "QCRH", "QUAD", "KWR", "PZN",
                             "QEP", "QTWO", "QK", "NX", "QRHC", "QUIK", "QUMU", "QUOT", "RBB", "RMED", "RICK", "RCMT",
                             "RCM", "REVG", "RFIL", "RLI", "RMG", "RES", "RH", "RPM", "RYB", "RLGT", "RFL", "RAND",
                             "RNDB", "RNGR", "PACK", "RAVE", "RAVN", "RJF", "RYAM", "ROLL", "RMAX", "RDI", "RLGY",
                             "REPH", "RLH", "RRBI", "RRGB", "RRR", "REED", "RGS", "RGLS", "RGA", "REKR", "RS", "RELV",
                             "RELX", "RBNC", "SOL", "RENN", "RBCAA", "FRBK", "REFR", "RSSS", "REZI", "RVP", "REV",
                             "REX", "REXN", "REYN", "RBKB", "RIBT", "RELL", "RMBI", "RNET", "REI", "REDU", "RVSB",
                             "RIVE", "RCKY", "RMCF", "ROG", "ROCH", "RDS-B", "RDS-A", "RBCN", "RMBL", "RUSHA", "RUSHB",
                             "RYAAY", "RYI", "STBA", "WORX", "SBFG", "SEIC", "SMHI", "SGBX", "SJW", "SM", "SP", "SRAX",
                             "SGRP", "SWKH", "SANW", "SFET", "SFE", "SGA", "JOE", "SLRX", "SALM", "SAL", "SD", "JBSS",
                             "SGMO", "SC", "SAR", "STSA", "SVRA", "SMIT", "SNDR", "SCHL", "SWM", "SAIC", "SMG", "SCPH",
                             "SCU", "SCYX", "SEB", "SBCF", "CKH", "SPNE", "EYES", "SECO", "SNFCA", "SEEL", "SIC",
                             "WTTR", "SEM", "SELB", "SLS", "LEDS", "SENEB", "SENEA", "SNES", "AIHS", "SXT", "SENS",
                             "SRTS", "SQNS", "SQBG", "SCI", "SERV", "SFBS", "SVT", "SESN", "SVBI", "SMED", "SHSP",
                             "SHEN", "TYHT", "SHG", "SHBI", "SIEB", "BSRR", "SIEN", "SRRA", "SIF", "SIFY", "SGLB",
                             "SGMA", "SBNY", "SLN", "SLGN", "SAMG", "SBOW", "SI", "SSNT", "SFNC", "SSD", "SHI", "SINO",
                             "TSLX", "SKX", "SKYS", "SWBI", "SNN", "SMBK", "SND", "SY", "SQM", "SCKT", "SWI", "SOI",
                             "SLNO", "SNGX", "SLDB", "XPL", "SAH", "SONM", "SON", "SNOA", "SOS", "SFBC", "SJI", "SPFI",
                             "SSB", "SFST", "SMBC", "SONA", "SPKE", "LOV", "SPPI", "SPB", "SPRO", "STXB", "SPOK",
                             "SBPH", "SFM", "SRAC", "STAF", "STND", "SMP", "SGU", "SCX", "MITO", "STCN", "SCS", "SCL",
                             "STXS", "STL", "SBT", "STRL", "STC", "SF", "SYBT", "BANX", "SRI", "STON", "SNEX", "SSKN",
                             "STRT", "STRS", "STRM", "MSC", "RGR", "SMFG", "SUMR", "SMMF", "SUM", "SSBI", "SMMT",
                             "WISA", "SXC", "SNDE", "SSY", "STG", "NOVA", "SCON", "SLGG", "SDPI", "SUP", "SGC", "SPRT",
                             "SURF", "SRGA", "SSSS", "STRO", "SUZ", "SWCH", "SYNL", "SYN", "SYPR", "SYBX", "SYX",
                             "CGBD", "TCF", "TELA", "TESS", "TFFP", "GLG", "TPIC", "TSRI", "TAIT", "TLC", "TAK", "TKAT",
                             "TALO", "TEDU", "TTM", "TAYD", "TCRR", "TISI", "TCCO", "TRC", "TEO", "TDY", "VIV", "TDS",
                             "TNAV", "TLGT", "TPX", "TS", "TENX", "TGC", "TEN", "TX", "TBNK", "TTI", "ODP", "NCTY",
                             "STKS", "THR", "KRKR", "TDW", "TLYS", "TSU", "TMBR", "TMST", "TWI", "TITN", "TLSA", "TMP",
                             "TR", "TRCH", "TTC", "TBLT", "TSQ", "TCON", "TW", "TACT", "TCI", "TRXC", "TGS", "TA",
                             "TREC", "TG", "THS", "TRVI", "TCBK", "TRS", "TRN", "TPHS", "TRT", "TPVG", "TBK", "TGI",
                             "TRST", "TRMK", "MEDS", "TTOO", "TC", "TOUR", "TKC", "TPB", "THCB", "THCA", "TPC", "XXII",
                             "TRWH", "TYME", "UFPT", "USAU", "USAK", "GROW", "UMRX", "USNA", "USCR", "USPH", "SLCA",
                             "ULBI", "UGP", "UA", "UNAM", "UFI", "UL", "UNB", "UFAB", "UBOH", "UCBI", "UBCP", "UFCS",
                             "UG", "UNFI", "UAMY", "USEG", "USLM", "USFD", "USWS", "UNTY", "UNVR", "UEIC", "UUU",
                             "USAP", "ULH", "UTI", "UVSP", "TIGR", "UONEK", "USIO", "ECOL", "UTMD", "VTVT", "EGY",
                             "VCNX", "VHI", "VALE", "VMI", "VALU", "VAPO", "VGR", "VEC", "VEDL", "PCVX", "VERO", "VRA",
                             "VNE", "VSTM", "VERB", "VBTX", "VRTV", "VCEL", "VRME", "VERY", "VRNA", "VRRM", "VRCA",
                             "VTNR", "VERU", "VRT", "VIACA", "VRAY", "VLGEA", "VNCE", "VIOT", "VIRC", "VHC", "VTSI",
                             "VRTS", "VSH", "VPG", "VIST", "VC", "VTGN", "VMAC", "VIVE", "VOLT", "VOYA", "VJET", "WTI",
                             "WDFC", "WSFS", "WVFC", "WPP", "VYNE", "WNC", "WAB", "WDR", "WD", "HCC", "WASH", "WSO-B",
                             "WSO", "WEI", "WBT", "WERN", "WSBC", "WCC", "WTBA", "WABC", "WSTL", "WLK", "WBK", "WWR",
                             "WEX", "WEYS", "WHF", "WLL", "FREE", "WOW", "WYY", "JW-A", "JW-B", "WHLM", "WVVI", "WSM",
                             "WLFC", "WSC", "WINT", "WGO", "WTT", "WETF", "WKEY", "WWW", "WF", "WRLD", "WOR", "XYF",
                             "XPO", "XPEL", "XTLB", "XELB", "XBIO", "XIN", "XOMA", "XTNT", "XFOR", "YPF", "YRCW",
                             "YELP", "YTEN", "YRD", "YIN", "YETI", "YORW", "DAO", "YGYI", "CTIB", "ZAGG", "ZEAL",
                             "ZDGE", "ZG", "ZSAN", "ZVO", "ZYNE", "BNSO", "DSWL", "ATIF", "BHVN", "BRLI", "CHNR",
                             "CCCL", "CCRC", "SXTC", "DOGZ", "CLWT", "GTEC", "HEBT", "HIHO", "HOLI", "HUSN", "LLIT",
                             "LKCO", "MTC", "NESR", "NTP", "NEWA", "NOMD", "SEED", "RETO", "SJ", "TANH", "PETZ", "MYT",
                             "WAFU", "ZKIN", "AAMC"]


def get_investing_lists():
    investment_list = investing_list_of_industrials + investing_list_of_technology + \
                      investing_list_of_communication_services + investing_list_of_energy + \
                      investing_list_of_utilities_and_real_estate + investing_list_of_materials + \
                      investing_list_of_consumer_discretionary + investing_list_of_consumer_staples + \
                      investing_list_of_healthcare + investing_list_of_financials + investing_list_of_oct_nov

    random.shuffle(investment_list)
    print(len(investment_list))
    return investment_list


def get_smaller_investing_lists():
    investment_list = investing_list_of_industrials + investing_list_of_technology + \
                      investing_list_of_communication_services + investing_list_of_energy + \
                      investing_list_of_utilities_and_real_estate + investing_list_of_materials + \
                      investing_list_of_consumer_discretionary + investing_list_of_consumer_staples + \
                      investing_list_of_healthcare + investing_list_of_financials
    return investment_list
# print(get_investing_lists())
